### ISSUE TITLE
使用React一个月的感受（我又来对比Vue了）

### ISSUE THREAD

**Issue by sysdog797** [sysdog797/syscoding#5]
###依然是数据更新方式
上篇文章也说到过React通过state同一管理到数据，并通过`this.setState()`更新（而且dom是异步更新的！）；而Vue可以直接改变实例中相对应的数值，并且刷新dom。
###v-if和v-show是真的好用
React中，需要通过模板字符串或者if语句进行一些数据的判断，从而控制dom的显示隐藏。下面是一些例子：
```javascript
// 情况一
let dom;
if(this.state.data){
    dom = <div></div>;
}else{
    dom = '';
}
// 情况二
<div className={`init-class${tihs.state.data ? '' : ' hide'}`}></div>  //注意这里的空格
```
反观vue里面直接用v-if或者v-show来控制即可2333。
这里需要注意：v-if 有更高的切换开销，而 v-show 有更高的初始渲染开销。因此，如果需要非常频繁地切换，则使用 v-show 较好；如果在运行时条件很少改变，则使用 v-if 较好。
```javascript
<div v-show="data" class="init-class"></div>
```
###<transition>
Vue中使用<transition>来控制一些过渡特效是一个神器，特别是结合v-show来写一些渐隐渐现的效果非常好用。搬运一个例子：
```javascript
<div id="demo">
  <button v-on:click="show = !show">
    Toggle
  </button>
  <transition name="fade">
    <p v-if="show">hello</p>
  </transition>
</div>
```
```css
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
```
在React框架里面有类似的插件，实现类似的动画`react-transition-group`，这个还是比较好用的，除了在处理元素隐藏显示的时候显得力不从心，这就显示处vue把动画和v-show结合在一起的好处了。
<br>
说了那么多React的“坏话”，其实React在也有自己的优势，在构建大型应用时其数据状态管理的透明度和可测试性、可维护性至关重要，更重要的优势是React生态中还有适用于Web端和原生APP的框架--React Native。
如果是单页应用数据相对不复杂的场景中，还是建议使用Vue作为框架来开发。（初级前端的个人观点...）
