### ISSUE TITLE
CSS实现button点击的涟漪效果

### ISSUE THREAD

**Issue by sysdog797** [sysdog797/syscoding#8]
顾名思义，就是点击按钮的时候，按钮上面有一个深色的圆圈扩散开来，就像是水面泛起的涟漪。简单分析下来，就是点击的时候，一个圆圈从小变大，同时不透明度也从半透明变成透明。
通常有两种方式来实现这个效果即JavaScript和CSS（这里主要记录CSS的方法，JavaScript简单介绍思路）。
这里先放上效果示意图：
![ripple-btn](https://raw.githubusercontent.com/sysdog797/syscoding/master/static/images/rippleBTN.gif)
首先看JavaScript实现方式：
> 1. 监听鼠标的点击事件，当点击按钮的时候，追加一个圆形的DOM
> 2. 改变DOM的大小和不透明度，直到能够完全的覆盖按钮
> 3. 移除圆圈
这个方法有它的优点也有缺点，缺点主要有：
> 1. 添加和移除DOM会导致页面的重绘
> 2. 绘制的时候要进行运算
不过这个方法可以方便灵活的实现从鼠标点击所在的位置实现涟漪效果，这是CSS不好做到的。
那，再来看CSS的实现方式，先上代码（这里用了less）：
```css
.button-ripple() {
    overflow: hidden;
    position: relative;
    transition: background-color .3s linear, border .3s linear;

    &:after {
        content: "";
        display: block;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        pointer-events: none;
        background-image: radial-gradient(circle, #000 10%, rgba(0, 0, 0, 0) 10.01%);
        background-repeat: no-repeat;
        background-position: 50%;
        transform: scale(10);
        opacity: 0;
        transition: transform .5s, opacity 1s;
    }

    &:active:after {
        transform: scale(0);
        opacity: .2;
        transition: 0s;
    }
}
```
这是一个less的mixin，直接在需要使用的地方如下操作即可：
```css
.ripple{
  .button-ripple();
}
```
这里利用:after伪元素画了一个遮罩层，当点击的时候遮罩缩小到0%，透明度为0.2，松开鼠标时还原遮罩层100%的大小，并将透明度缩小到0。
